//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomitWebJob
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueMessage
    {
        public int Id { get; set; }
        public string MessageBody { get; set; }
        public Nullable<System.DateTime> MessageOn { get; set; }
    }
}
